### ISSUE TITLE
signin.aws.amazon.com says network failure

### ISSUE THREAD

**Issue by cloudk9** [aws-samples/saml-cli-userscript#1]
signin.aws.amazon.com says network failure when programmatic access is selected

**Comment by TonyFNZ** [comment]
Hello @cloudk9, can you please confirm which browser you are using?

**Comment by cloudk9** [comment]
Tested with Chrome and Edge. Same issue.

**Comment by TonyFNZ** [comment]
Thanks for raising this issue.  I have confirmed the script is working in Firefox, but fails in Chrome and Edge.  The root cause is the `Content-Security-Policy` header which is returned from the server when the page loads - this is unlikely to be fixable in the short term.

I have updated the ReadMe on this project to inform users of this limitation in 18f3ac7.
